### ISSUE TITLE
create_from_surface error when exported for Android

### ISSUE THREAD

**Issue by sworvish** [PiCode9560/Godot-4-Concave-Mesh-Slicer#3]
``E 0:00:05:0736   create_from_surface: Index r[i] = 56439 is out of bounds (vcount = 24).
  <C++ Source>   scene/resources/mesh_data_tool.cpp:72 @ create_from_surface()
``
When slicing a mesh, it simply disappears and throws this error. 

- This only happens on mobile
- I have tried using all 3 available renderers
- I have also tried testing your included example on mobile
- I am using Godot v4.0.3.stable.official [5222a99f5]

Many thanks for making this script, and thanks in advance for reading this!

**Comment by aahmyu** [comment]
Having the same issue on 4.2.

**Comment by PiCode9560** [comment]
> Having the same issue on 4.2.

Are you using it on mobile? Because, Godot 4.2 in windows works fine for me
