### ISSUE TITLE
2d concave polygon support?

### ISSUE THREAD

**Issue by illogicalapple** [PiCode9560/Godot-4-Concave-Mesh-Slicer#5]
no idea how much of the code would need to be modified

**Comment by PiCode9560** [comment]
You want to slice 2d concave polygons?

**Comment by illogicalapple** [comment]
yeah, just kinda hoping it wouldn't be too hard to do off this

**Comment by PiCode9560** [comment]
It's probably easier to create it from scratch. Maybe you could try using geometry2D to do it.
[https://docs.godotengine.org/en/stable/classes/class_geometry2d.html](url)
[https://www.youtube.com/watch?v=mnDsqD3S1YY](url)

Also, I found this if you're interested: [https://github.com/lupoDharkael/godot-sprite-slicing](url)
