### ISSUE TITLE
How you learn mesh slicing?

### ISSUE THREAD

**Issue by HeavyRail0451** [PiCode9560/Godot-4-Concave-Mesh-Slicer#6]
What kind of books you read?

**Comment by PiCode9560** [comment]
I didn't read any book. I just do my research online and maybe combine many techniques into one, or just tried to figure it out myself.
Here are some resources that helped me learned this:
https://www.youtube.com/watch?v=BVCNDUcnE1o&t=8s
https://www.geometrictools.com/Documentation/TriangulationByEarClipping.pdf
